Repository cloudflare/circl, pull requests merged in 2021-08, with the labels that each got.

#259 sign: adds benchmark function for signature schemes
  sign/schemes/schemes_test.go
Labels: cosmetic

#258 bls12: hash to G1 complaint with h2c draft
  ecc/bls12381/constants.go
  ecc/bls12381/ec2.go
  ecc/bls12381/ff/common.go
  ecc/bls12381/ff/cyclo6.go
  ecc/bls12381/ff/cyclo6_test.go
  ecc/bls12381/ff/fp.go
  ecc/bls12381/ff/fp12.go
  ecc/bls12381/ff/fp12_test.go
  ecc/bls12381/ff/fp2.go
  ecc/bls12381/ff/fp2_test.go
  ecc/bls12381/ff/fp6.go
  ecc/bls12381/ff/fp6_test.go
  ecc/bls12381/ff/fp_test.go
  ecc/bls12381/ff/scalar.go
  ecc/bls12381/ff/scalar_test.go
  ecc/bls12381/ff/uroot.go
  ecc/bls12381/ff/uroot_test.go
  ecc/bls12381/g1.go
  ecc/bls12381/g1Isog.go
  ecc/bls12381/g1_test.go
  ecc/bls12381/g2.go
  ecc/bls12381/gt.go
  ecc/bls12381/hash_test.go
  ecc/bls12381/pair.go
  ecc/bls12381/pair_test.go
  ecc/bls12381/testdata/BLS12381G1_XMD-SHA-256_SSWU_NU_.json
  ecc/bls12381/testdata/BLS12381G1_XMD-SHA-256_SSWU_RO_.json
Labels: changesAPI

#261 bls12: removing SetInt64 method
  ecc/bls12381/ff/fp.go
  ecc/bls12381/ff/scalar.go
  go.mod
  go.sum
Labels: changesAPI

#264 bls12: adding efficient subgroup checking method for G1
  ecc/bls12381/constants.go
  ecc/bls12381/g1.go
  ecc/bls12381/g1_test.go
  internal/test/test.go
Labels: enhancement

#268 Bump to go 1.17
  .github/workflows/ci-actions.yml
Labels: maintenance

#265 Optimize multiplication and make it constant time
  ecc/bls12381/ff/fp2.go
  ecc/bls12381/g1.go
  ecc/bls12381/g2.go
Labels: enhancement

#266 Watson/fast g2 check
  ecc/bls12381/constants.go
  ecc/bls12381/g2.go
  ecc/bls12381/g2_test.go
  ecc/bls12381/psi_test.go
Labels: enhancement
