Repository cloudflare/circl, pull requests merged in 2022-06, with the labels that each got.

#337 Wait for amd64 job succeds to run other jobs.
  .github/workflows/ci-actions.yml
Labels: maintenance

#336 sike mitigation with test cases
  dh/sidh/internal/p434/core.go
  dh/sidh/internal/p434/curve.go
  dh/sidh/internal/p434/curve_test.go
  dh/sidh/internal/p503/core.go
  dh/sidh/internal/p503/curve.go
  dh/sidh/internal/p503/curve_test.go
  dh/sidh/internal/p751/core.go
  dh/sidh/internal/p751/curve.go
  dh/sidh/internal/p751/curve_test.go
  dh/sidh/internal/templates/core.gotemp
  dh/sidh/internal/templates/curve.gotemp
  dh/sidh/internal/templates/curve_test.gotemp
  dh/sidh/sidh_test.go
Labels: fix-A-bug

#338 Formatting auto-generated code.
  dh/sidh/internal/templates/gen.go
  kem/kyber/gen.go
  kem/kyber/kyber1024/kyber.go
  kem/kyber/kyber512/kyber.go
  kem/kyber/kyber768/kyber.go
  kem/sike/gen.go
  pke/kyber/gen.go
  sign/dilithium/gen.go
Labels: cosmetic

#339 Format templates using gtfmt tool
  dh/sidh/internal/templates/arith_decl.gotemp
  dh/sidh/internal/templates/arith_generic.gotemp
  dh/sidh/internal/templates/arith_test.gotemp
  dh/sidh/internal/templates/core.gotemp
  dh/sidh/internal/templates/curve.gotemp
  dh/sidh/internal/templates/curve_test.gotemp
  dh/sidh/internal/templates/fp2.gotemp
  dh/sidh/internal/templates/fp2_test.gotemp
  kem/kyber/templates/pkg.templ.go
  pke/kyber/templates/params.templ.go
  pke/kyber/templates/pkg.templ.go
  sign/dilithium/templates/mode.templ.go
  sign/dilithium/templates/modePkg.templ.go
  sign/dilithium/templates/params.templ.go
Labels: cosmetic

#340 Format generated files.
  dh/sidh/internal/p434/core.go
  dh/sidh/internal/p434/curve.go
  dh/sidh/internal/p434/curve_test.go
  dh/sidh/internal/p503/core.go
  dh/sidh/internal/p503/curve.go
  dh/sidh/internal/p503/curve_test.go
  dh/sidh/internal/p751/core.go
  dh/sidh/internal/p751/curve.go
  dh/sidh/internal/p751/curve_test.go
Labels: cosmetic
