Repository cloudflare/circl, pull requests merged in 2023-05, with the labels that each got.

#436 Releasing CIRCL v1.3.3
  CITATION.cff
  README.md
Labels: maintenance

#430 internal: add TurboShake{128,256}
  internal/sha3/keccakf.go
  internal/sha3/sha3.go
  internal/sha3/sha3_test.go
  internal/sha3/shake.go
  pke/kyber/internal/common/sample.go
  sign/dilithium/mode2/internal/sample.go
  sign/dilithium/mode2aes/internal/sample.go
  sign/dilithium/mode3/internal/sample.go
  sign/dilithium/mode3aes/internal/sample.go
  sign/dilithium/mode5/internal/sample.go
  sign/dilithium/mode5aes/internal/sample.go
  simd/keccakf1600/example_test.go
  simd/keccakf1600/f1600x.go
  simd/keccakf1600/f1600x2_arm64.go
  simd/keccakf1600/f1600x2_arm64.s
  simd/keccakf1600/f1600x4_amd64.go
  simd/keccakf1600/f1600x4_amd64.s
  simd/keccakf1600/f1600x4stubs_amd64.go
  simd/keccakf1600/f1600x_test.go
  simd/keccakf1600/fallback.go
  simd/keccakf1600/internal/asm/go.mod
  simd/keccakf1600/internal/asm/go.sum
  simd/keccakf1600/internal/asm/src.go
Labels: new feature

#431 Kangaroo12 draft -10
  internal/sha3/sha3.go
  internal/sha3/shake.go
  xof/k12/k12.go
  xof/k12/k12_test.go
Labels: new feature

#440 Set CIRCL version for generated assembler code.
  go.sum
  pke/kyber/internal/common/amd64.s
  pke/kyber/internal/common/asm/go.mod
  pke/kyber/internal/common/asm/go.sum
  pke/kyber/internal/common/stubs_amd64.go
  sign/dilithium/internal/common/amd64.s
  sign/dilithium/internal/common/asm/go.mod
  sign/dilithium/internal/common/asm/go.sum
  sign/dilithium/internal/common/stubs_amd64.go
Labels: fix-A-bug
